### ISSUE TITLE
Seperation of user-service

### ISSUE THREAD

**Issue by KwanHW** [CS3219-AY2223S1/cs3219-project-ay2223s1-g33#127]
# Description

**Comment by sharpstorm** [comment]
Considering the level of coupling between the intended `User-Service` and `User-BFF-Service`, it has been elected to implement both under a single User-Service, but with a clear distinction of 2 separate modules. `User-BFF-Service` (renamed to `User-Service`), will make loopback GRPC calls to `User-Service` (renamed to `User-Crud-Service`
